### ISSUE TITLE
Unable to Stream with direct Link

### ISSUE THREAD

**Issue by Salesgokul** [iRedScarf/onedrive-index#12]
Hey first of all thanks for creating the index.

after successfully installing the index I am not able to stream videos with the index direct link. I tried MX,VLC etc
but when i put the direct link on the browser it is downloading correctly.
so where is the issue. pls help.

**Comment by iRedScarf** [comment]
This project is based on the original [onedrive-vercel-index](https://github.com/spencerwooo/onedrive-vercel-index) with added convenience for deployment and improved security measures. The streaming video functionality was not developed by me, so I cannot guarantee its full support. In my personal usage, clicking on the icons for `IINA`, `VLC`, `PotPlayer`, and `nPlayer` from the video page successfully streams the content using the corresponding software. However, the smoothness of streaming depends on the size of the video file and the user's network conditions. As the content needs to be transferred from Microsoft's OneDrive server to the local device, and considering that Microsoft's OneDrive server may not be well optimized for video streaming, I currently do not have a satisfactory solution to address your issue.
