### ISSUE TITLE
Can anyone make video or help with making index or show me my mistakes?

### ISSUE THREAD

**Issue by Miclicks** [iRedScarf/onedrive-index#13]
I did every step that is told, I have my app (client) id that i created, i made obfuscated client secret. In user principal id i wrote my mail:" something@sth.onmicrosoft.com". My base directory is: "/Index files". And password protected files that i configured in vercel were in directory: "/Index files/test1,/Index files/test2". Also i already set the api permissions: user.read, files.read.all, offline_access. When i open site after deploying on vercel all i got is that. When i deploy and see whats vercel building i see that messages:

<html>
<body>

oredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
--
17:21:43.858 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:43.912 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:43.912 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:44.183 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:44.185 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:44.185 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:44.186 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:44.386 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:44.386 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:44.690 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:44.691 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:45.541 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:45.541 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:45.541 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:45.541 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:45.709 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:45.710 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:46.639 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:46.640 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:46.640 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:46.640 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:47.447 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:47.447 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:48.278 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:48.279 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
17:21:48.333 | info  - Generating static pages (0/18)
17:21:48.424 | info  - Generating static pages (4/18)
17:21:48.430 | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
17:21:48.430 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

</body>
</html>

When i visit site i see only that: https://pasteboard.co/zguBROM2WABo.png
Please help me;(

**Comment by kaiser62** [comment]
How did you fix it?
