### ISSUE TITLE
Can we get in-built PDF viewer & Image grid view 

### ISSUE THREAD

**Issue by DamnYatin** [iRedScarf/onedrive-index#19]
When ever I open a pdf in the index it makes me download it. Can we get an in-built pdf viewer?
And can there automatically be grid view whenever we open images section like you can set that the folder named 'Photos' or 'Images' be open automatically to grid view

**Comment by hirockstar** [comment]
named will not be good option to do that what you can do is that if have folder has only images and video then it will open in FolderGridLayout you can do that. in that will be more reliable.

but you have to do it by your self.


for pdf this pkg will be helpfull
https://www.npmjs.com/package/@react-pdf-viewer/core

**Comment by testingsonit** [comment]
Please mark the issue as completed

**Comment by iRedScarf** [comment]
Thank you for the great suggestion! I agree this would be a very useful feature to have.
Unfortunately, I don't have the capacity to work on implementing this right now as I need to focus on some other critical priorities. My time and resources are quite limited currently.
If you're interested in taking a stab at implementing this yourself, I'd be more than happy to review a pull request from you.
