### ISSUE TITLE
Can I use my own Redis instance without using Upstash ?

### ISSUE THREAD

**Issue by sachinsenal0x64** [iRedScarf/onedrive-index#22]

**Comment by sachinsenal0x64** [comment]
NVM its working

![image](https://github.com/iRedScarf/onedrive-index/assets/127573781/fc1d7738-d141-47ed-9462-ecfcdb546f85)

**Comment by iRedScarf** [comment]
It's theoretically possible, but I haven't verified it. You can try it.

**Comment by sachinsenal0x64** [comment]
> It's theoretically possible, but I haven't verified it. You can try it.

Thanks, it's working, but I have to manually SET env
