### ISSUE TITLE
Initial Step 3/3: invalid_client

### ISSUE THREAD

**Issue by Lumysia** [iRedScarf/onedrive-index#4]
Hi, Greetings and thank you for your valuable efforts.  
I kindly request your assistance in guiding me towards a resolution for the current predicament.

## What happened

- Followed [Getting Started](https://github.com/iRedScarf/onedrive-index/issues/new#getting-started) section
- I encountered an issue while attempting to obtain OAuth authentication during `Step 3/3: Retrieving access and refresh tokens`. An error message was displayed stating, `Whoops, it appears that we have encountered a problem: invalid_client`.

## Logs

```txt
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
 Trace ID: 2cbdbd67-1bb8-4da3-8456-b8d2a47e4100
 Correlation ID: 7faed391-0c0a-4104-add8-ffae24069f1e
 Timestamp: 2023-09-29 07:54:00Z
```

- [Microsoft's official explanation](https://login.microsoftonline.com/error?code=7000218)

## Attempts

- https://github.com/spencerwooo/onedrive-vercel-index/issues/683
- https://github.com/spencerwooo/onedrive-vercel-index/issues/684
- Regrettably, despite my thorough investigation, I have been unable to locate any pertinent information of significance.

## ScreenShot

![Screenshot 2023-09-29 at 16 05 33](https://github.com/iRedScarf/onedrive-index/assets/40706446/65a2abf6-4394-4e7a-9720-609da93a7c52)

**Comment by hirockstar** [comment]
> Hi, Greetings and thank you for your valuable efforts. I kindly request your assistance in guiding me towards a resolution for the current predicament.
> 
> ## What happened
> * Followed [Getting Started](https://github.com/iRedScarf/onedrive-index/issues/new#getting-started) section
> * I encountered an issue while attempting to obtain OAuth authentication during `Step 3/3: Retrieving access and refresh tokens`. An error message was displayed stating, `Whoops, it appears that we have encountered a problem: invalid_client`.
> 
> ## Logs
> ```
> AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
>  Trace ID: 2cbdbd67-1bb8-4da3-8456-b8d2a47e4100
>  Correlation ID: 7faed391-0c0a-4104-add8-ffae24069f1e
>  Timestamp: 2023-09-29 07:54:00Z
> ```
> 
> * [Microsoft's official explanation](https://login.microsoftonline.com/error?code=7000218)
> 
> ## Attempts
> * [(Stuck Step 3/3) Whoops, looks like we got a problem: invalid_client. spencerwooo/onedrive-vercel-index#683](https://github.com/spencerwooo/onedrive-vercel-index/issues/683)
> * [(Stuck Step 3/3) Whoops, looks like we got a problem: invalid_client. spencerwooo/onedrive-vercel-index#684](https://github.com/spencerwooo/onedrive-vercel-index/issues/684)
> * Regrettably, despite my thorough investigation, I have been unable to locate any pertinent information of significance.
> 
> ## ScreenShot
> ![Screenshot 2023-09-29 at 16 05 33](https://user-images.githubusercontent.com/40706446/271509311-65a2abf6-4394-4e7a-9720-609da93a7c52.png)

are you using your own client id and secret key?? also did you [Obfuscate ](https://ovi.swo.moe/docs/advanced#modify-configs-in-apiconfigjs)your client secret too?

**Comment by Lumysia** [comment]
Yes, it's a completely new client that I have created within the Azure Control Panel.

**Comment by Lumysia** [comment]
> Yes, it's a completely new client that I have created within the Azure Control Panel.

With the correct Client ID, Client Secret, Permissions, and redirect URL.

**Comment by Lumysia** [comment]
Apologies for not encrypting the Client Secret value. Thank you for bringing it to my attention!

**Comment by hirockstar** [comment]
no problem
