### ISSUE TITLE
Error to connect on microsoft

### ISSUE THREAD

**Issue by dsakura** [iRedScarf/onedrive-index#5]
My account is E5, and I'm getting this error when trying to log in.
`AADSTS900144: The request body must contain the following parameter: 'client_id'.`

I have another question, off topic, about E5, can I made here? write to you?
Many thanks

**Comment by therockstarind** [comment]
share SSR

**Comment by dsakura** [comment]
Sorry but what is SSR?
This one?
`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=&redirect_uri=http%3A%2F%2Flocalhost&response_type=code&scope=user.read+files.read.all+offline_access&response_mode=query`
Thank you

**Comment by therockstarind** [comment]
SSR is ScreenShot 
BTW in your URL there is Client id is missing you have to get them from [onedrive ](https://ovi.swo.moe/docs/advanced#using-your-own-clientid-and-clientsecret-1) this can help you to generate the client and secret id.

**Comment by iRedScarf** [comment]
It looks like you didn't set the Client_ID properly.

**Comment by therockstarind** [comment]
Q.It looks like you didn't set the Client_ID properly?
A. Well I didn't do anything.

Q.BTW, it is not recommended that you make the Client_ID public.
A. you can make it public but not the secret id.

**Comment by iRedScarf** [comment]
> SSR 是 您 URL 中的屏幕截图，缺少客户端 ID，您必须从[OneDrive](https://ovi.swo.moe/docs/advanced#using-your-own-clientid-and-clientsecret-1)获取它们，这可以帮助您生成客户端和秘密 ID。

Yes, refer to this link to get your own Client ID and Client Secret and set them correctly in the environment variables. And don't make them public (otherwise I wouldn't have to set them in environment variables).

**Comment by therockstarind** [comment]
couldn't get it what are you trying to say?

**Comment by iRedScarf** [comment]
Bro, I'm answering @dsakura

**Comment by therockstarind** [comment]
oh sorry I did not see it was you my bad

**Comment by dsakura** [comment]
I start clicking the deploy buttom here, and add the variables on the vercel setup. Do I need to clone this repository too?
![onedriveid2](https://github.com/iRedScarf/onedrive-index/assets/4233324/a85cb17e-fb6e-4566-951e-175cce44168f)
![onedriveid](https://github.com/iRedScarf/onedrive-index/assets/4233324/26fa0f37-9055-4709-89a0-2fdeefe840dd)

The request id and correlation id showed on the error are diferent from the NEXT_PUBLIC_CLIENT_ID that I copied from the azure, i checked now. Thanks an sorry my bad english

**Comment by iRedScarf** [comment]
If you click the deploy button directly in [README.md](https://github.com/iRedScarf/onedrive-index/blob/main/README.md), there is no need to clone [this repository](https://github.com/iRedScarf/onedrive-index) (Vercel will automatically clone this repository and create a private repository for you).

At the same time, among your environment variables, only `NEXT_PUBLIC_SITE_TITLE` needs to use the `NEXT_PUBLIC_` prefix. 

Several other environment variables do not need to use the `NEXT_PUBLIC_` prefix. They are `USER_PRINCIPAL_NAME`, `BASE_DIRECTORY`, `CLIENT_ID`, `CLIENT_SECRET `.

I guess the problem you encountered may be because `USER_PRINCIPAL_NAME`, `BASE_DIRECTORY`, `CLIENT_ID`, and `CLIENT_SECRET` use the `NEXT_PUBLIC_` prefix?

**Comment by iamwho001** [comment]
![Screenshot (4)](https://github.com/iRedScarf/onedrive-index/assets/49368101/d22cecd7-5b25-437c-b67e-d7a0cea36fe8)
 im getting this error

**Comment by dsakura** [comment]
Ah problaby its that! Im traveling by now, but I'll teste edit the variables names. Many thanks @iRedScarf !

**Comment by iRedScarf** [comment]
You're welcome. Have a good trip :D

**Comment by dsakura** [comment]
Many thanks. Now I have this error:
```
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 3e6cd518-6999-4d25-9476-9b5d7a741c00
Correlation ID: 7ffb7bc2-29ea-4d3f-9b61-5cd68b450a4a
Timestamp: 2023-10-20 16:28:19Z
```
need to be an App Registration or a Business Application? Thanks

nm this... I was anxious and forgot to obfuscate the secret. Sorry. But this message its normal?
![vercel](https://github.com/iRedScarf/onedrive-index/assets/4233324/a875958e-f8cf-403e-9c92-d4aff782bd6c)

**Comment by 3kh0** [comment]
Yeah I am also getting this error, all the env vars have the correct names

![image](https://github.com/iRedScarf/onedrive-index/assets/58097612/6ac4394d-545b-412d-9895-83f7dfd7bf27)

and I got this error:

![image](https://github.com/iRedScarf/onedrive-index/assets/58097612/68ee39a2-7a45-4154-89d7-8f0e5be2b689)

with the Microsoft wiki saying this:
```
Error Code | 70002
Message | Client  application name '{appName}' is not valid or the credentials used to  authenticate the client could not be understood by the server.
Remediation | Developer error - the app is attempting to sign in without the necessary or correct authentication parameters.
```

Any ideas?

**Comment by dsakura** [comment]
@3kh0 do you obsfuscate your secret value?

**Comment by 3kh0** [comment]
> @3kh0 do you obsfuscate your secret value?

No, it is just stored in plain text

**Comment by dsakura** [comment]
@3kh0 Try obsfucate. https://ovi.swo.moe/docs/advanced#modify-configs-in-apiconfigjs 
Change the valor and do the redeploy again

**Comment by 3kh0** [comment]
@dsakura Ah ok, that worked, thank you so much!

**Comment by dsakura** [comment]
I changed the address I want to share, I made sure I was logged into the right account that has the API and OneDrive, and I continue to receive this message "Do not pretend to be the site owner".

Do I need to conect to vercel with same microsoft account?

**Comment by dsakura** [comment]
Well, I delete everything and restart, perfect! Sorry bother with many messages and again, thank you very much! 
One doubt: how I set a folder with name that have space between the words? Thanks

**Comment by iRedScarf** [comment]
You can completely copy and paste the directory name on/back. 

For example, the complete directory path with spaces in the directory name is `/share/a and b/`, where `/share` is the folder where the content you want to share (meaning that you are not sharing the entire OneDrive folder), `/share/a and b/` is you If you need an encrypted folder, you can fill in `/share` in `BASE_DIRECTORY` and `/a and b` in `NEXT_PUBLIC_PROTECTED_ROUTES`. If there are multiple encrypted directories, you can separate them with a `,`.

The following are the settings of my Demo page, in which `BASE_DIRECTOY` is filled in `/`, which means that I am sharing the entire OneDrive directory. There are two folders that require password access, namely `Secret 1 (pw=Demo)` and `Secret 2 (Take-a-guess)`. Note that they all have spaces and other symbols, and are case-sensitive (to avoid possible errors).

![image](https://github.com/iRedScarf/onedrive-index/assets/37926645/67a3f6d8-ee61-4ff5-acfa-452c0c317cf6)
