### ISSUE TITLE
Error to connect

### ISSUE THREAD

**Issue by dsakura** [iRedScarf/onedrive-index#8]
It was working, without problems, and without any configuration changes, I have this error. Thanks!
This message appears on the screen as an error
https://privatebin.net/?310844f44184e3dd#GyaLQBhXuP63JSfNSCM2h3gvyADrCaTpYXGxbqcGARdC
`Press F12 and open devtools for more details, or seek help at [onedrive-index discussions](https://github.com/iRedScarf/onedrive-index/discussions).`
And from F12:
https://privatebin.net/?484cc10c173ac677#BkbH2vtUStejsAN2uBRP6N55qSPh8LgPRWssUZHdrZmB

**Comment by iRedScarf** [comment]
Sorry, I don't quite understand what you mean by re-auth? What is the specific situation you need to implement?

**Comment by dsakura** [comment]
I copied from another issue and forgot to erase it. The error is the messages that i sent on privatebin. Can't connect again. How can I fix it? I think it's a problem with authenticating the account. Many thanks

**Comment by Tuanpluss02** [comment]
Just re-deploy it

**Comment by iRedScarf** [comment]
Yes, just re-deploy it.

**Comment by dsakura** [comment]
Already made it, from the vercel, without success. Need to re-deploy from here? Deleting my vercel project. Thanks

**Comment by iRedScarf** [comment]
Yes, delete the project on Vercel, delete the repository that was automatically created on GitHub by the last deployment, then redeploy and auth again.

If the library automatically created on GitHub by the last deployment has modified code, you can also enter a different project name when deploying Vercel.

In fact, you can deploy OneDrive-Index of multiple different Microsoft accounts, but it should be noted that the project names must be different, and the value of `KV_PREFIX` in the environment variable cannot be the same.

**Comment by dsakura** [comment]
Okay, I'll redo it, I only use it with one account. Is it something that I will have to redo more often or a bug that initially doesn't occur much? Thanks!

**Comment by dsakura** [comment]
hmm same error after re-deploy everything.. the authenticate window started to load and then the same error message came.

**Comment by Tuanpluss02** [comment]
Please note that you must use another Redis project; otherwise, the old access token and refresh token will be used for authentication. Good luck!

**Comment by iRedScarf** [comment]
Yes, as @Tuanpluss02 said, when you redeploy a OneDrive-Index with the same account, you must reset the Redis database you used. The easiest way to understand is to delete the old database and build a new one.

**Comment by dsakura** [comment]
oh I'll try it! in fact I used the previous redis. Thanks, soon I report about it

**Comment by dsakura** [comment]
Nice! Now everything working again! Many thanks again!
